# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'colors.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(330, 199)
        font = QtGui.QFont()
        font.setFamily("Rubik ExtraBold")
        font.setBold(True)
        font.setWeight(75)
        Settings.setFont(font)
        self.formLayoutWidget = QtWidgets.QWidget(Settings)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 331, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rubik ExtraBold")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rubik ExtraBold")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.text_color = QtWidgets.QPushButton(self.formLayoutWidget)
        self.text_color.setObjectName("text_color")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.text_color)
        self.background_color = QtWidgets.QPushButton(self.formLayoutWidget)
        self.background_color.setObjectName("background_color")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.background_color)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rubik ExtraBold")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.buttons_color = QtWidgets.QPushButton(self.formLayoutWidget)
        self.buttons_color.setObjectName("buttons_color")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.buttons_color)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rubik ExtraBold")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.slider_handle_color = QtWidgets.QPushButton(self.formLayoutWidget)
        self.slider_handle_color.setObjectName("slider_handle_color")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.slider_handle_color)
        self.default = QtWidgets.QPushButton(self.formLayoutWidget)
        self.default.setObjectName("save_all_colors")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.default)
        self.load_theme = QtWidgets.QPushButton(self.formLayoutWidget)
        self.load_theme.setObjectName("load_theme")
        self.load_theme.setText("Load theme")
        self.export_theme = QtWidgets.QPushButton(self.formLayoutWidget)
        self.export_theme.setObjectName("export_theme")
        self.export_theme.setText("Export theme")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.load_theme)
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.export_theme)
        self.slider_groove_color = QtWidgets.QPushButton(self.formLayoutWidget)
        self.slider_groove_color.setObjectName("slider_groove_color")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.slider_groove_color)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rubik ExtraBold")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)


    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Form"))
        self.label.setText(_translate("Settings", "Text"))
        self.label_2.setText(_translate("Settings", "Background"))
        self.text_color.setText(_translate("Settings", "Change Color"))
        self.background_color.setText(_translate("Settings", "Change Color"))
        self.label_3.setText(_translate("Settings", "Buttons"))
        self.buttons_color.setText(_translate("Settings", "Change Color"))
        self.label_4.setText(_translate("Settings", "Slider handle"))
        self.slider_handle_color.setText(_translate("Settings", "Change Color"))
        self.default.setText(_translate("Settings", "Default"))
        self.slider_groove_color.setText(_translate("Settings", "Change Color"))
        self.label_5.setText(_translate("Settings", "Slider groove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QWidget()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())
