# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/test_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtSvg
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAbstractItemView


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.setFixedSize(475, 564)
        self.MainWindow.setStyleSheet(open("data/css/main.css", 'r').read())
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.timeMusic = QtWidgets.QSlider(self.centralwidget)
        self.timeMusic.setGeometry(QtCore.QRect(0, 150, 271, 22))
        self.timeMusic.setOrientation(QtCore.Qt.Horizontal)
        self.timeMusic.setObjectName("timeMusic")
        self.buttonPlay = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPlay.setGeometry(QtCore.QRect(100, 20, 91, 91))
        self.buttonPlay.setText("")
        self.buttonPlay.setObjectName("buttonPlay")
        self.previousTrack = QtWidgets.QPushButton(self.centralwidget)
        self.previousTrack.setGeometry(QtCore.QRect(10, 40, 75, 61))
        self.previousTrack.setText("")
        self.previousTrack.setObjectName("previousTrack")
        self.nextTrack = QtWidgets.QPushButton(self.centralwidget)
        self.nextTrack.setGeometry(QtCore.QRect(200, 40, 75, 61))
        self.nextTrack.setText("")
        self.nextTrack.setObjectName("nextTrack")
        self.repeat_btn = QtWidgets.QCheckBox(self.centralwidget)
        self.repeat_btn.setGeometry(QtCore.QRect(0, 210, 51, 17))
        self.repeat_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.repeat_btn.setText("")
        self.repeat_btn.setObjectName("repeat_btn")
        self.volume = QtWidgets.QSlider(self.centralwidget)
        self.volume.setGeometry(QtCore.QRect(110, 210, 160, 22))
        self.volume.setOrientation(QtCore.Qt.Horizontal)
        self.volume.setObjectName("volume")
        self.volume.setMinimum(-1)
        self.volume.setMaximum(102)
        self.volume.setValue(30)
        self.volume_icon = QtSvg.QSvgWidget("src/volume-up-fill.svg", parent=self.centralwidget)
        self.volume_icon.setGeometry(80, 205, 30, 30)
        self.downloadFromWeb = QtWidgets.QPushButton(self.centralwidget)
        self.downloadFromWeb.setGeometry(QtCore.QRect(80, 250, 75, 23))
        self.downloadFromWeb.setText("")
        self.downloadFromWeb.setObjectName("downloadFromWeb")
        self.addMusic = QtWidgets.QPushButton(self.centralwidget)
        self.addMusic.setGeometry(QtCore.QRect(0, 250, 75, 23))
        self.addMusic.setText("")
        self.addMusic.setObjectName("addMusic")
        self.settings = QtWidgets.QPushButton(self.centralwidget)
        self.settings.setGeometry(QtCore.QRect(160, 250, 75, 23))
        self.settings.setIcon(QIcon("src/settings.svg"))
        self.listMusic = QtWidgets.QListWidget(self.centralwidget)
        self.listMusic.setGeometry(QtCore.QRect(0, 280, 271, 261))
        self.listMusic.setObjectName("listMusic")
        self.playlist_it = QtWidgets.QListWidget(self.centralwidget)
        self.playlist_it.setGeometry(QtCore.QRect(280, 0, 191, 450))
        self.playlist_it.setObjectName("playlist_it")
        self.now_time_music = QtWidgets.QLabel(self.centralwidget)
        self.now_time_music.setGeometry(QtCore.QRect(0, 180, 35, 13))
        self.now_time_music.setText("")
        self.now_time_music.setObjectName("now_time_music")
        self.all_time_music = QtWidgets.QLabel(self.centralwidget)
        self.all_time_music.setGeometry(QtCore.QRect(245, 180, 35, 13))
        self.all_time_music.setText("")
        self.all_time_music.setObjectName("all_time_music")
        self.add_music_to_playlist = QtWidgets.QPushButton(self.centralwidget)
        self.add_music_to_playlist.setGeometry(QtCore.QRect(280, 500, 191, 40))
        self.add_music_to_playlist.setText("Add music to playlist")
        self.add_music_to_playlist.setObjectName("add_music_to_playlist")
        self.create_new_playlist = QtWidgets.QPushButton(self.centralwidget)
        self.create_new_playlist.setGeometry(QtCore.QRect(280, 450, 191, 40))
        self.create_new_playlist.setText("Create new playlist")
        self.create_new_playlist.setObjectName("create_new_playlist")
        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.setSettingForElements()

    def setSettingForElements(self):
        self.listMusic.setSelectionMode(QAbstractItemView.SingleSelection)
        self.playlist_it.setSelectionMode(QAbstractItemView.SingleSelection)
        self.repeat_btn.setIcon(QIcon("src/repeat-1.svg"))
        self.downloadFromWeb.setIcon(QIcon("src/cloud-arrow-down-fill.svg"))
        self.buttonPlay.setIcon(QIcon("src/play-circle-fill.svg"))
        self.buttonPlay.setIconSize(QtCore.QSize(70,70))
        self.nextTrack.setIcon(QIcon("src/skip-forward-fill.svg"))
        self.nextTrack.setIconSize(QtCore.QSize(50, 50))
        self.previousTrack.setIcon(QIcon("src/skip-backward-fill.svg"))
        self.previousTrack.setIconSize(QtCore.QSize(50, 50))
        self.addMusic.setIcon(QIcon("src/music-note-list.svg"))
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
